---
- name: Include RedHat setup tasks
  ansible.builtin.include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian setup tasks
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml

- name: Include SSL tasks
  ansible.builtin.include_tasks: ssl.yml

- name: Include plugins tasks
  ansible.builtin.include_tasks: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
