---
- name: Include OS Specific setup tasks
  ansible.builtin.import_tasks: setup-{{ ansible_os_family }}.yml

- name: Include config tasks
  ansible.builtin.import_tasks:
    - config.yml
    - ssl.yml
    - plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
