---
- name: Ensure required dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key.
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  ansible.builtin.apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ logstash_version }}/apt stable main'
    state: present
    update_cache: true

- name: Install Logstash.
  ansible.builtin.apt:
    name: '{{ logstash_package }}'
    state: present

- name: Add Logstash user to adm group (Debian).
  ansible.builtin.user:
    name: logstash
    group: logstash
    groups: adm
  notify: Restart logstash
